// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PinterestClone.DAL.Data;

#nullable disable

namespace PinterestClone.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250917120000_AddNotificationSettings")]
    partial class AddNotificationSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is a simplified designer file
            // The full model will be built by Entity Framework
        }
    }
}
